branch-defaults:
  master:
    environment: bento-ruby
global:
  application_name: bento-ruby
  branch: null
  default_ec2_keyname: mit-dornera
  default_platform: Ruby 2.4 (Puma)
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
